services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: financial_tracker_admin
      POSTGRES_DB: financial_tracker_db
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: